### ISSUE TITLE
Variable number of PCA components

### ISSUE THREAD

**Issue by arnodelorme** [sccn/roiconnect#1]
See code at the end of roi_activity (after "return"). The indices for PCA components need to be given to the data2spwctrgc as input in roi_connect. Simply save the individual PCA components in EEG.roi.nPCA and recompute the indices as done in roi_activity (after "return").

**Comment by nguyen-td** [comment]
This has been solved a long time ago for both data2spwctrgc (which we don't use anymore) and data2sctrgcmim.
