### ISSUE TITLE
CS always infinite

### ISSUE THREAD

**Issue by arnodelorme** [sccn/roiconnect#18]
Would you mind running the pipeline_connectivity script? There is a problem with CS (always infinite) and it is unclear why.

**Comment by fpellegrini** [comment]
I just ran the script with the latest roiconnect version but for me, the CS looks fine (complex values in the usual range). I'm not sure where the difference could come from. I'm using eeglab v2021.1 . Maybe there is an incompatibility with higher versions? I'll try re-running it with the latest eeglab version in the next days.

**Comment by arnodelorme** [comment]
Thank you Franziska,

These are the values I get. Are you getting the same?

EEG.roi.CS(1:5,1:5)

ans =

   1.0e+11 *

   0.0000 + 0.0000i   2.3436 + 0.0000i  -0.6248 + 0.0000i  -0.1161 + 0.0000i  -1.9398 + 0.0000i
   0.0000 + 0.0000i   1.2302 + 0.0000i  -0.1147 + 0.0455i  -0.0914 - 0.0255i  -0.8435 - 0.0871i
   0.0000 + 0.0000i   0.3801 + 0.0000i   0.0209 + 0.0090i  -0.0180 - 0.0394i  -0.1292 - 0.0100i
   0.0000 + 0.0000i   0.2536 + 0.0000i   0.0088 + 0.0155i   0.0134 - 0.0255i  -0.1415 + 0.0750i
   0.0000 + 0.0000i   0.1750 + 0.0000i   0.0211 + 0.0392i   0.0164 - 0.0078i  -0.1288 + 0.0339i

**Comment by arnodelorme** [comment]
Thanks

**Comment by nguyen-td** [comment]
I know it's a very old Issue but I tested it myself just now, the values seem quite small (as they should be?):

EEG.roi.CS(1:5,1:5)

ans =

   0.0090 + 0.0000i   0.0074 + 0.0000i   0.0002 + 0.0000i   0.0007 + 0.0000i  -0.0021 + 0.0000i
   0.0047 + 0.0000i   0.0032 + 0.0003i   0.0011 - 0.0006i  -0.0002 + 0.0003i  -0.0011 + 0.0004i
   0.0015 + 0.0000i   0.0005 + 0.0000i   0.0006 - 0.0004i  -0.0001 + 0.0003i  -0.0003 + 0.0006i
   0.0010 + 0.0000i   0.0005 - 0.0003i   0.0005 - 0.0002i  -0.0000 - 0.0000i  -0.0003 + 0.0005i
   0.0007 + 0.0000i   0.0005 - 0.0001i   0.0004 - 0.0000i   0.0000 - 0.0001i  -0.0002 + 0.0002i

I will close it for now, feel free reopen.
