### ISSUE TITLE
roi_plotbrainmovie missing

### ISSUE THREAD

**Issue by Hiyeri** [sccn/roiconnect#27]
The function `roi_plotbrainmovie` is called in https://github.com/sccn/roiconnect/blob/fa9b779e54fe150df9f6fe7f91c1a3eeb0082b36/pop_roi_connectplot.m#L451
but it is not part of the toolbox yet (maybe not pushed yet?). @arnodelorme, would you be so kind to add it?

**Comment by arnodelorme** [comment]
roi_plotbrainmovie requires the brainmovie plugin to be installed
