### ISSUE TITLE
FOOOF

### ISSUE THREAD

**Issue by arnodelorme** [sccn/roiconnect#38]
The documentation of pop_roi_activity and roi_activity mentions

```
%  'fooof'            - ['on'|'off'] enable FOOOF analysis. Default is 'off'.
%  'fooof_frange'     - [ ] FOOOF fitting range. Default is [1 30] like in the
%                      example.
```

However, it is unclear what "FOOOF" means and the example mentioned is not present.

**Comment by Hiyeri** [comment]
FOOOF refers to the method described [here](https://fooof-tools.github.io/fooof/). The example refers to the [script](https://github.com/fooof-tools/fooof_mat/blob/main/examples/fooof_example_one_spectrum.m) in the corresponding Matlab wrapper (the original method is implemented in Python). I could definitely extend the documentation and add the corresponding links to make it more clear, what do you think?
