### ISSUE TITLE
Snippet

### ISSUE THREAD

**Issue by arnodelorme** [sccn/roiconnect#44]
Instead of snippets, 2 seconds epochs should be created and then split into snippets. The current issue is that the code in pop_roi_connect ignores "boundary" events.

1. Create the maximum number of epochs of 2-second length
2. Divide them into groups of 60. This is the snippet.
3. Run on each groups of 60
4. If there are epochs remaining, put out a warning message

**Comment by stefanhaufe** [comment]
Hi Arno, Tien,

this is not completely clear to me. What is a situation where you would want to cut the 2s epochs further into snippets?

THanks and best wishes,
Stefan

**Comment by fpellegrini** [comment]
I think what Arno meant is that should we first create epochs and afterwards group them into snippets (e.g., with 60 epochs each). I'm not sure what the problem with the boundary events is, but Tien and me will look into it.

**Comment by arnodelorme** [comment]
The goal would be to simply see if we can speed up computation, by performing matrix multiplication in parallel (the snippet are independent so couldn’t they be grouped in matrices). Now, with 10 snippets we multiply computation time by about 7.

**Comment by nguyen-td** [comment]
How about trying to extend the connectivity functions directly then? We could try to keep the way the snippets are computed as is, but then pass all of them at the same time as a big matrix to the functions. Is that the idea?

**Comment by arnodelorme** [comment]
Yes, sure. Whatever works that is not too complicated to see if we can speed up computation.

**Comment by nguyen-td** [comment]
Should be solved with #71, it should be faster now. Please reopen if there are any issues.
