### ISSUE TITLE
negative coherence

### ISSUE THREAD

**Issue by CPernet** [sccn/roiconnect#48]
I somehow managed the obtain negative coherence values ?? that seem problematic
very standard way to compute stuff, as per @arnodelorme s' code https://github.com/LIMO-EEG-Toolbox/RestingState/blob/main/code/Rest_pipeline.m#L114

**Comment by fpellegrini** [comment]
Thanks for pointing us to this issue. This is an error in the documentation, i.e., COH stands for (complex-valued) coherency and not for coherence (as the documentation mistakenly said). We will the fix the documentation and provide the possibility for calculating coherence and imaginary coherency as well. Sorry for any inconvenience.

**Comment by nguyen-td** [comment]
Thanks for the report! #49 adresses this issue, so it should be solved now.
