### ISSUE TITLE
New options not added to uilist causing error in pop_roi_connect

### ISSUE THREAD

**Issue by edwardwl** [sccn/roiconnect#52]
Hello, 

I think 'cCOH', 'aCOH', 'iCOH' have not been added to the uilist in pop_roi_connect and are causing errors on lines 140-142. 

    %if out.ccoh,   methods = [ methods { 'cCOH' } ]; end
    %if out.acoh,   methods = [ methods { 'aCOH' } ]; end
    %if out.icoh,   methods = [ methods { 'iCOH' } ]; end

**Comment by 99KHayes** [comment]
This is what we found too, we were able to workaround by not using the GUI

**Comment by nguyen-td** [comment]
Thanks a lot for reporting. When I introduced the new methods cCOH, aCOH and iCOH I only tested them through the command line so it is indeed a GUI issue. I will provide a fix by next week!

**Comment by nguyen-td** [comment]
Should be fixed now with #51. Please reopen if the error still persists.
