### ISSUE TITLE
ROIconnect: compute ROI connectivity error

### ISSUE THREAD

**Issue by tysonperez** [sccn/roiconnect#54]
![error](https://github.com/sccn/roiconnect/assets/33464158/b750a453-18c7-46d1-8f6e-952f7e24ea97)

Can compute ROI activity but get this error when trying to compute any ROI connectivity measure (e.g. MIM, GC, TRGC) from the GUI.  This is only an issue with the newest release of ROIconnect and was not an issue with the older version ROIconnect that we utilized back in May, 2023.

**Comment by nguyen-td** [comment]
Thanks for the report, it's probably related to #52. We recently replaced the variable "COH" with aCOH (coherence) and further introduced cCOH (complex-valued coherency) and iCOH (absolute value of the imaginary part of coherency) to avoid ambiguity. I tested the new changes from the command line but not from the GUI yet. I aim to provide a fix by next week.

**Comment by nguyen-td** [comment]
Should be fixed now with #51. Please reopen the issue if the error still persists.
