### ISSUE TITLE
Error with brain movie plotting

### ISSUE THREAD

**Issue by nguyen-td** [sccn/roiconnect#66]
I am trying to plot the brain movie using 
`pop_roi_connectplot(EEG, 'measure', 'MIM', 'plot3d', 'on',  'plotcortex', 'off');` but I get the following errors:

> Warning: Error creating or updating Surface
>  Error in value of property  XData
>  Array is wrong shape or size 
> Warning: Error creating or updating Surface
>  Error in value of property  XData
>  Array is wrong shape or size 

The figure shows briefly but closes immediately. I am using the pipeline_connectivity pipeline with the Colin27_5003 head model.

**Comment by nguyen-td** [comment]
Despite the errors, it ended up working. I didn't know `roi_brainmovie` creates a file.

**Comment by arnodelorme** [comment]
Let me have a look
