### ISSUE TITLE
brainmovie scaling

### ISSUE THREAD

**Issue by arnodelorme** [sccn/roiconnect#69]
Setting the correct threshold to show areas, maybe using percentile. Show only the 10% most connected regions.

**Comment by nguyen-td** [comment]
I realized that the roi_plotbrainmovie script is part of the brainmovie plugin and not ROIconnect. I can make the change and create a pull request there.

**Comment by arnodelorme** [comment]
Yes, please do that. We could integrate the brainmovie code to the plugin if we decide to (merge the two plugins).

**Comment by nguyen-td** [comment]
Solved in mentioned issue.
