### ISSUE TITLE
Handling of the maximum value of “freq range” in pop_roi_connectplot.m function (also pop_roi_statsplot.m).

### ISSUE THREAD

**Issue by sato16** [sccn/roiconnect#84]
Dear roiconnect developer,

I found that the maximum value was not included when I set input value of `freq range` in `pop_roi_connectplot.m` (also `pop_roi_statsplot.m`). 
I was confused about this design because I thought the maximum value would be included when freq range set. (e.g. EEGLAB's standard function [timefreq.m processes including the maximum value](https://github.com/jadesjardins/eeglab_data_annotate_demo/blob/c4d0d29ad1fd69bcf6323fd2ea6a4e7cf5c69f1b/demo_proj/analysis/support/dependencies/eeglab/functions/timefreqfunc/timefreq.m#L239C8-L239C110).)
Is this an intended design for some kind of analysis? Or is it just simply a bug?

If this is a bug, fixing [the line 395 in  pop_roi_connectplot.m](https://github.com/sccn/roiconnect/blob/81336ddc84d0c21e1bb6c28a74e9817efcc95285/pop_roi_connectplot.m#L395
) and  [the line 73 in  pop_roi_statsplot.m](https://github.com/sccn/roiconnect/blob/81336ddc84d0c21e1bb6c28a74e9817efcc95285/pop_roi_statsplot.m#L73C16-L73C87) will solve it as shown below
`Before: frq_inds = find(S.freqs >= g.freqrange(1) & S.freqs < g.freqrange(2));`

`After: frq_inds = find(S.freqs >= g.freqrange(1) & S.freqs <= g.freqrange(2));`

I'd appreciate if you could answer this question. 

Best Regards,
Fumiaki

**Comment by nguyen-td** [comment]
Hi Fumiaki,

This seems to be a bug but we (@Wirkungstreffer and myself) will have a closer look and fix it accordingly. Ideally, both the minimum values and maximum values should be included. 

I will leave this issue open until we have fixed it.

Thanks,
Tien

**Comment by sato16** [comment]
Hi Tien,
Thank you for your response. Sure, I will keep this page unclosed.  I feel this toolbox is excellent and it would be my pleasure to help improve it. So if there is anything I can help with, such as reproducing bugs or providing additional information, please let me know.
Best,
Fumiaki

**Comment by sato16** [comment]
Thank you for modifying the code!
Should I close this issue?

**Comment by nguyen-td** [comment]
Oh yes, thanks for poking!
